### ISSUE TITLE
How to add a max limit on the burn function with solidity?

### ISSUE THREAD

**Issue by descartes2100** [ethereum/solidity-blog#140]
How to add a max limit on the burn function with solidity? Actually accumulating the max amount of tokens and triggering the burn function as soon as the max amount reaches? That is, the fee is paid by the end user who reaches the limit. We don't want this situation to happen, what can we do alternatively? Can you help me? Thank you.

**Comment by franzihei** [comment]
Hi, this is not the right place for Solidity support questions. Consider checking out [Ethereum StackExchange](https://ethereum.stackexchange.com/) or the [Solidity Chat](https://gitter.im/ethereum/solidity).

**Comment by descartes2100** [comment]
Ok, thanks you so much.
