### ISSUE TITLE
[Blog Post] Immutable feature

### ISSUE THREAD

**Issue by franzihei** [ethereum/solidity-blog#27]
We want to write a blog post about the new `immutable` feature. It will be part of the `Solidity 0.6.x features` series. 

## Workflow

- [x]  @chriseth or @ekpyron to draft post on **HackMD**
- [x]  (technical) accuracy review on HackMD
- [x]  @franzihei style/content review on HackMD
- [x] create PR in this repo
- [x] final review
- [x]  merge PR / publish blog post

## Deadline
This post should be published until XX/XX/XXXX.

## Link to draft post on HackMD

**Comment by franzihei** [comment]
ping @ekpyron @chriseth what's the timeline on this blog post? :)

**Comment by ekpyron** [comment]
I pretty much forgot about this plan... @chriseth do you have time for sketching a post? If not, just assign me to this issue, so that I won't forget again, and I'll try to write something up the next days.

**Comment by franzihei** [comment]
Ping @ekpyron would be cool if we could share something about `immutable` next week-ish, so that it's not too far away from the actual release where we added this feature. :)

**Comment by ekpyron** [comment]
Yeah, I'm trying to get to it this week, I hope I can find the time.

**Comment by franzihei** [comment]
Just added a few bullets to my comment above, maybe helpful as a rough outline. : )

**Comment by ekpyron** [comment]
First draft: https://hackmd.io/Hc51VzpnSBC6VqOkR_QJ-w

**Comment by franzihei** [comment]
PR is ready here: https://github.com/ethereum/solidity-blog/pull/42
@chriseth you wanna have a look and push the button? :)

**Comment by franzihei** [comment]
published here: https://solidity.ethereum.org/2020/05/13/immutable-keyword/
