### ISSUE TITLE
Make a post of every release?

### ISSUE THREAD

**Issue by axic** [ethereum/solidity-blog#31]
I think if we were to do this, it should contain the short intro from the release page (and perhaps the changelog) and the link to the release. But I wouldn't copy paste the entire release page with all the different links.

Any opinions?

Also not suggesting we should do this retroactively for every release, but we may as well if it can be automated. Probably there is a github API to download the release text.

**Comment by chriseth** [comment]
Sounds good! Should we include the changelog or not?
At some point, we might also have a table with all releases on `solidity.ethereum.org` - github only lists them in the order of publication, not sorted by version.

**Comment by franzihei** [comment]
I can offer to start creating a small blog post for every release, similar like we tweet about every release. It should not include too much text though, should it?

**Comment by chriseth** [comment]
Sounds good!

**Comment by franzihei** [comment]
I think we decided to have a small release announcement for every release now, we started with 0.6.8. I can be in charge of putting it together / reminding us that we want to write one each time.

**Comment by axic** [comment]
This issue was also suggesting that we could create a script pulling from github release page and pushing it to the blog.

Should we keep it open for that for a tiny bit longer?

**Comment by franzihei** [comment]
I don't think it's a good idea to "automate" release announcements like that since we might want to outline things more in the blog post, e.g. in the last one we outlined the three bugs in more detail. Or what are you suggesting?

**Comment by axic** [comment]
The release page on github was always written like a blog post, highlighting the important parts. I know recently highlighting on the blog became even more emphasized, but still, the old release notes were trying to fill in the same gap. (They are not just a copy paste from the CHANGELOG file.)

The suggestion here is to have a script which pulls the release page and creates a blog entry for each for **the past releases**.

I wasn't suggesting to use it for any new release, but I guess it could be.

**Comment by axic** [comment]
Here's the API to download release notes: https://developer.github.com/v3/repos/releases/

**Comment by axic** [comment]
Here's my script:
```
var https = require('https')
var MemoryStream = require('memorystream')
var fs = require('fs')

function getReleaseNotes(version, cb) {
  var mem = new MemoryStream(null, { readable: false });
  https.get(
    'https://api.github.com/repos/ethereum/solidity/releases/tags/' + version,
    { headers: { 'User-Agent': 'Mozilla/5.0' } },
    function (response) {
    if (response.statusCode !== 200) {
      console.log('Error downloading file: ' + response.statusCode);
      process.exit(1)
    }
    response.pipe(mem);
    response.on('end', function () {
      cb(mem.toString())
    })
  })
}

function createNote(version, date, body) {
  var note = `---
layout: post
published: true
title: 'Solidity ${version} Release Announcement'
date: '${date}'
author: Solidity Team
category: Releases
---

${body}

A big thank you to all contributors who helped  make this release possible!

Download the new version of Solidity [here](https://github.com/ethereum/solidity/releases/tag/v${version}).
  `

  fs.writeFileSync(`${date}-solidity-${version}-release-announcement.md`, note)
}

function processVersion(version) {
  console.log(`Creating note for ${version}`)
  getReleaseNotes('v' + version, function (releaseNote) {
    // Assume this works.
    releaseNote = JSON.parse(releaseNote)

    var body = releaseNote.body
    // Replace DOS newlines
    body = body.replace(/(\r\n)/gm, '\n')
    // Strip separators, `---` or `----`
    body = body.replace(/(\-\-\-*)/gm, '')
    // Replace too many consecutive new lines
    body = body.replace(/(\n\n\n*)/gm, '\n')
    // Strip stuff after 'We especially thank'
    body = body.replace(/(We especially thank[\s\S]*)$/gm, '')
    // Replace first mention with URL
    body = body.replace(`Solidity version ${version}`, `[Solidity v${version}](https://github.com/ethereum/solidity/releases/tag/v${version})`)
  
    var date = releaseNote.published_at.match(/\d\d\d\d-\d\d-\d\d/)[0]

    createNote(version, date, body)
  })
}

processVersion('0.6.0')
processVersion('0.6.1')
processVersion('0.6.2')
processVersion('0.6.3')
processVersion('0.6.4')
processVersion('0.6.5')
processVersion('0.6.6')
processVersion('0.6.7')
```

**Comment by franzihei** [comment]
Looks good from what I can tell, @chriseth can you also have a look so that we can move forward? :)

**Comment by chriseth** [comment]
looks good

**Comment by franzihei** [comment]
Minor comment, there's two spaces between `helped` and `make` in this sentence: `A big thank you to all contributors who helped  make this release possible!`.

**Comment by axic** [comment]
That was fixed locally, just forgot to push here (also added some other things, iirc).
