### ISSUE TITLE
Introduce post categories (similar to blog.ethereum.org)

### ISSUE THREAD

**Issue by axic** [ethereum/solidity-blog#33]
The categories I suggest (or the plural form of these):
- Release
- Tutorial
- Update / Announcement

@franzihei @chriseth What do you think?

This could especially make sense if we do #31 to aid search-ability.

**Comment by chriseth** [comment]
Are bugs part of 'announcement'? Should they have their own category?

Also "Tutorial" does not really catch what we are doing, I think. More like "explainer"

**Comment by axic** [comment]
> Are bugs part of 'announcement'? Should they have their own category?

Maybe "Security (advisory)" ?

> Also "Tutorial" does not really catch what we are doing, I think. More like "explainer"

Explainer sounds good too.

**Comment by franzihei** [comment]
Cool I like the idea and I would also tend to add another category for bugs (maybe `security alert`)?

**Comment by axic** [comment]
On blog.ethereum.org it is just "Security", apparently.

**Comment by axic** [comment]
How about these:
- Announcements
- Releases (or Release announcements)
- Security alerts
- Explainers

**Comment by franzihei** [comment]
I'm on it. :)

**Comment by franzihei** [comment]
Still missing: Color-coding for the category labels and maybe other config/settings

# Colors for the categories

- Announcements: #5D92E3
- Explainers: #CE66A4
- Releases: #F1C73F
- Security Alerts: #F0978B

**Comment by franzihei** [comment]
Now done done with https://github.com/ethereum/solidity-blog/pull/58
