### ISSUE TITLE
Make syntax highlighting work for the blog.

### ISSUE THREAD

**Issue by chriseth** [ethereum/solidity-blog#34]
There is already a pull request in the rouge syntax highlighter repository: https://github.com/rouge-ruby/rouge/pull/760

We could create our own package of rouge that has this PR merged (with some modifications to make it 0.6.0-compatible).

**Comment by franzihei** [comment]
What's the current status on this? @axic any news on your PR to github-pages?

**Comment by axic** [comment]
I've chased them up again, will try to do it without github-pages next week if no response. Would also prefer all the other blog configuration is finished before we tackle this, because it means changing all the gems/build.
