### ISSUE TITLE
Copy some more posts

### ISSUE THREAD

**Issue by axic** [ethereum/solidity-blog#37]
Potentially copy over these too:
- https://blog.ethereum.org/2016/11/09/analysis-storage-corruption-bug/ (this was a response to https://blog.ethereum.org/2016/11/01/security-alert-solidity-variables-can-overwritten-storage/)
- https://blog.ethereum.org/2016/03/30/solidity-available-in-visual-studio/

**Comment by franzihei** [comment]
Can copy them once the categories have added to add them in one go, too.

**Comment by axic** [comment]
I think it would be nice to copy these now as the configuration of the blog is fully figured out.
