### ISSUE TITLE
Solidity 0.6.x features: Overview of topics for the series

### ISSUE THREAD

**Issue by franzihei** [ethereum/solidity-blog#39]
_moved from https://github.com/ethereum/solidity/issues/8057_

TO DO before 0.7:
- [x] **virtual and override, public vars can override external functions, abstract contracts, no state variable shadowing** #38 
- [ ] **push(element) / push() / disallow write access to .length**

Done:
- [x] fallback / receive split
- [x] try/catch 
- [x] array slices

Postpone / possibly mention in other blog posts:
- [ ] global enums and structs (can be covered alongside free functions explanation)
- [ ] type(a**x) = type(a), payable(x) conversion for address, f.address instead of address(f)
- [ ] `_` delimiter for hex strings
- [ ] ABIEncdoreV2 no longer experimental, yul optimizer activated together with standard optimizer
- [ ] new error reporter
- [ ] disable metadata hash / switch to ipfs / swarm
- [ ] modifier depth in source mappings
- [ ] multiple @returns statements in natspec
- [ ] yul / inline assembly: leave

**Comment by chriseth** [comment]
Why assigned to me?

**Comment by franzihei** [comment]
Because the issue was assigned to you in the solidity repo, I thought maybe you wanted to keep it in your head. :) I just didn't want to change it in case it was needed for you as a reminder or something. But if not, then feel free to unassign and assign me!

**Comment by chriseth** [comment]
Ah ok sorry! I don't use assignments - they don't work well with my email-based github workflow :)

**Comment by franzihei** [comment]
closing this since we're at 0.7 now
