### ISSUE TITLE
Summit closing blog post

### ISSUE THREAD

**Issue by axic** [ethereum/solidity-blog#61]
Shouldn't there be a closing blog post listing all the video links? Or linking to the archive site?

Likewise, how about the findings from the summit surveys? They were posted on twitter, it would be nice to have them shared in a post too.

**Comment by franzihei** [comment]
I could write one up this week if we don't think it's too late!

**Comment by axic** [comment]
I think it is not late :)

**Comment by franzihei** [comment]
Started drafting here, hope to have it ready by tomorrow.  https://hackmd.io/oyAATX6uRVm04Aeh26PGZw

The only think I would put in a separate post are the outcomes from the pre-conference survey (most liked & hated stuff about Solidity etc.).

**Comment by franzihei** [comment]
Here's the finished post: https://hackmd.io/oyAATX6uRVm04Aeh26PGZw 

Feel free to leave notes in the HackMD if you think something is missing or weird, otherwise I'll create a PR for the post on Monday next week. :)

**Comment by axic** [comment]
Added my comments.
