### ISSUE TITLE
Consider changing the URL to include the "blog" prefix

### ISSUE THREAD

**Issue by axic** [ethereum/solidity-blog#65]
From https://github.com/ethereum/solidity/pull/8735#discussion_r413402396:
> Concerning stability of the URLs: Maybe the blog posts should be under solidity.ethereum.org/blog/date/post

I guess here @chriseth anticipates we move the blog to a different URL.

However I think it would be possible to leave as-is and add a redirect to `solidity.tld/blog/...` once we have a new domain with a landing page and more than a blog.

**Comment by chriseth** [comment]
blog.solidity.tld?

**Comment by axic** [comment]
Closing since we decided to use blog.soliditylang.org
