### ISSUE TITLE
Team introduction article

### ISSUE THREAD

**Issue by axic** [ethereum/solidity-blog#69]
Would an article about past and present team members (and special mentions of external contributors?) make sense?

Or perhaps a short interview article with each members, one at a time?

@chriseth @franzihei opinion?

**Comment by franzihei** [comment]
I'm not entirely sure if we want to put the people so much in the spotlight of the blog? I really like the idea of highlighting the team in the 5-year-retrospective post though!

**Comment by axic** [comment]
> I'm not entirely sure if we want to put the people so much in the spotlight of the blog?

Why is that a bad thing? I think everyone is proud of their work, but obviously can opt out.

**Comment by franzihei** [comment]
We can check what people would feel about the idea in the next team meeting on Wednesday.
