### ISSUE TITLE
Update kramdown (security alert)

### ISSUE THREAD

**Issue by franzihei** [ethereum/solidity-blog#90]
There has been a security advisory published by Github to update Kramdown due to a vulnerability found: https://github.com/ethereum/solidity-blog/network/alert/Gemfile.lock/kramdown/open

It can be fixed with

```
gem "kramdown", ">= 2.3.0" 
```

but I don't know if that's gonna break anything in the blog's current setup?

**Comment by axic** [comment]
We cannot change it and have to wait for github-pages to update.
